#steps:
#- name: 'gcr.io/cloud-builders/git'
#  args: ['push', 'https://github.com/ethentest13/test.git', 'master']
#  args: ['push', 'https://source.developers.google.com/p/$PROJECT_ID/r/$REPO', 'master']
#https://github.com/ethentest13/test.git

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
images: ['gcr.io/$PROJECT_ID/quickstart-image']
#  tags: ['gcp-cloud-build-sample-build']
