#steps:
#- name: 'bash'
#  args: ['./quickstart.sh']

#steps:
#- name: 'gcr.io/cloud-builders/gcloud'
#  entrypoint: 'bash'
#  args: [ '-c', 'curl -i https://rcl222.com' ]

#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
#images:
#- 'gcr.io/$PROJECT_ID/quickstart-image'
#  tags: ['gcp-cloud-build-sample-build']

steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args:
#  - gcloud container clusters get-credentials function-test --zone asia-east1-a --project rcl2021-300903
  - get
  - pods
  - -n
  - ethentest2
#  - set
#  - image
#  - deployment
#  - nginx-test
#  - nginx=gcr.io/rcl2021-300903/nginx:latest
  env:
  - 'CLOUDSDK_CORE_PROJECT=rcl2021-300903'
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=function-test'
options:
  pool:
    name: 'projects/rcl2021-300903/locations/asia-east1/workerPools/ethen-test-privatepool'
#  workerPool: projects/rcl2021-300903/locations/asia-east1/workerPools/ethen-test-privatepool
