steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['push', 'https://github.com/ethentest13/test.git', 'master']
#  args: ['push', 'https://source.developers.google.com/p/$PROJECT_ID/r/$REPO', 'master']
#https://github.com/ethentest13/test.git
