steps:
- name: 'bash'
  args: ['./quickstart.sh']

#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
#images:
#- 'gcr.io/$PROJECT_ID/quickstart-image'
#  tags: ['gcp-cloud-build-sample-build']
